### ISSUE TITLE
Confused by some of your shader code

### ISSUE THREAD

**Issue by TheCelticGuy** [gasgiant/FFT-Ocean#3]
Hey, me again.

I've so far got most of the FFT understood now but I am confused by some parts of your code.

You have permute shader which I don't know what that is or where it comes from? I see no mention of it in Tessendorf.

Also your scale shader pass is also confusing you have:

```[numthreads(8, 8, 1)]
void Scale(uint3 id : SV_DispatchThreadID)
{
	Buffer0[id.xy] = Buffer0[id.xy] / Size / Size;
}
```
This equates to **(xy*Scale) / Scale** which basically simplifies to **xy** so you're not scaling anything since **scale/scale =1**..?

Shouldn't it be:

```
[numthreads(8, 8, 1)]
void Scale(uint3 id : SV_DispatchThreadID)
{
	Buffer0[id.xy] = Buffer0[id.xy] / (Size * Size);
}
```
I am basing it on this iDFT equation:

![image](https://user-images.githubusercontent.com/33559521/109437090-04e8bf80-7a1b-11eb-8132-e483f085853b.png)

Also i am very confused by the cascade stuff, does each cascade require its own FFT for DY DX DZ ? How did you chose the numbers:

```
    [SerializeField]
    float lengthScale0 = 250;
    [SerializeField]
    float lengthScale1 = 17;
    [SerializeField]
    float lengthScale2 = 5;
```

Are these numbers arbitrary or is there a calculation you made to determine the ideal cascade scales?

Thanks!

**Comment by gasgiant** [comment]
Hi! 

1) About permute. You are right, there is nothing about it in Tessendorf. He doesn't go into nitty-gritty details of FFT implementation. Tessendorf only shows sum of waves by "all wave vectors". In practive you have to transalte it into a double sum. And because of how wave vectors are defined the result differs from actual FFT definition by -1 multiplier for some indices. Permute simply corrects for that. You can read about it here in paragraph 4.1 
https://tore.tuhh.de/bitstream/11420/1439/1/GPGPU_FFT_Ocean_Simulation.pdf  
Though there is a mistake in their derivation. They write inverse FFT using the standart definition that has multiplyer 1 / N^2. It makes sense as a reverse operation for FFT of size N. However our sum of waves is definded in such a way, that scale factor 1 / N^2 is unnesessary. They get away with the mistake, because they use Phillips spectrum defined by Tessendorf. This spectrum has an arbitrary constant, so in the end it doesn't matter. For empirical spectrums I use it does matter a lot, because they have a specific magnitude that will be messed up. Also this scale multiplyier creates an annoying link between simulation resolution and the strength of the waves that we don't want.

2) For computer 1 / x / x  = 1 / (x * x). It is not "divide by x divided by x", but simply "divide by x two times". I think 1 / (x * x) might be better in shaders, because division is more expensive than multiplication. But compared to all the other stuff I do there the difference is negligible. 
The Scale kernel is actually not invoked by the ocean simulation, because as I said earlier, the specific flavour of IFFT it uses doesn't require scaling. But I have it just in case someone wants to use this FFT implementation for other purpouses.

3) About cascades. Yes each of them requires their own IFFTs for both displacements and derivatives. I don't have a good rule for choosing the cascades length scales. A good thing for the neighbouring cascades is to have coprime length scales, to fight tiling. But it's something I just eyeball for now. You can toggle "Always recalculate initials" to see the results live in play mode.
There is also a big question of setting the wavenumber domains of the cascades. I'm thinking about writing an editor tool for dealing with all that.
