### ISSUE TITLE
Visible gap between tiles/rings.

### ISSUE THREAD

**Issue by vrguru** [gasgiant/FFT-Ocean#5]
Hi. Really nice work.

However I notice rendering artefacts on top/right edge of each Ring.
It is present both in the Editor and in the gameview.
Looks like it is off by one?

![image](https://user-images.githubusercontent.com/325605/144737234-9b5baa6f-d3e1-472a-832d-dd8b0edd51fb.png)

**Comment by gasgiant** [comment]
Hi! I don't see the artifacts on the screenshot. I've also never seen the artifatcs specifically in one corner. However there are some irregularities on the borders of the LOD levels of the mesh, most visible in the corners. The reason is that in this version the jump in mesh density is very sudden. It is solvable with geomorphing. I implemented it in the newer version, but it is not yet ready to be released.

**Comment by vrguru** [comment]
The artefacts are the gray lines on the top/right of each tile. ( to the right in the image).
The orange boxes are the selected ones (which hides their tile edges).

Ok good to hear about an update. Impressive stuff really!
Do you have any suggestion on how one would go about to extract the heights in a certain area, if one would like to use them for hydrodynamic simulation?

I would like to extract a region around a ship and get all the heights so I can drive a heightfield used for buoyancy, lift, drag calculations.

**Comment by gasgiant** [comment]
Could you please screenshot the atrifact more clearly? 

With regards to height chek out this talk https://www.gdcvault.com/play/1023320/Fixed-Point-Iteration-A-Simple 
To get the data from the GPU you can use https://docs.unity3d.com/ScriptReference/Rendering.AsyncGPUReadback.html
You can readback the whole displacement texture and sample it on the cpu or you can do the boyancy physics on the GPU in compute shader and readback the results.

**Comment by vrguru** [comment]
Here are the artefacts pretty visible:

![image](https://user-images.githubusercontent.com/325605/144746649-660ba570-a11d-4eab-868d-acac5fc2d768.png)
![image](https://user-images.githubusercontent.com/325605/144746656-b5a73ca6-b751-493a-a78c-bc6aa81cc15a.png)

**Comment by gasgiant** [comment]
Oops, that's definitely a bug with mesh placement and not a subtle thing with LOD. I am kind of surprized I never encountered it. 

I have an idea why could this happen though, but fixing it would be difficult because the code for the mesh placement is a mess. It is fixed in the new version with gemorphing because the vertices are placed in the vertex shader and are a part of a single mesh, so this bug isn't really possible. 

This is waht I'm going to do. For a long time I was planning a complete rework with a different shader and a lot more features, such as underwater, shoreline, foam particles and compute buoyancy physics. Some of it is ready and some is not. However I have pretty much finished reworked simulation that solves the significant performance problems of the original. Also the reworked mesh doesn't have sharp LOD borders and this bug. I think it all warrants an update for the simulation and the mesh code without all the planned features. I'll try to do it by the end of december, but no promises.

**Comment by gasgiant** [comment]
Unfortunately, I haven't had time to work on the updated version. I made the repository with a newer version public (see link in the readme). It is unfinished, but certainly better than what I have in this one.

**Comment by vrguru** [comment]
Ah, I downloaded that one and...the rendering is not quite the same no.

![image](https://user-images.githubusercontent.com/325605/166208599-9cd7e0ae-0d67-4912-bf16-0d8b71ac24ce.png)

I tried to find some settings but there is none that changes this.
I suppose asking for the bugfix in the old code would be asking too much?
