### ISSUE TITLE
How does getWaterHeight works 

### ISSUE THREAD

**Issue by davidAlgis** [gasgiant/FFT-Ocean#7]
Hi, 

First thanks for this beautiful code and video. 
I have a question regarding the function that get the water height in CPU : `WaveGenerator::GetWaterHeight()`. 
How does it works ? Why is it not just the sum of the height of all cascades ? 

Thanks in advance

**Comment by gasgiant** [comment]
Hi! It is addressed in the video. Cascades hold not height, but displacement vectors, and these have a horizontal part. Because of that we can't simply sample Y component of the displacement, because it represents height over a different point, offset from the one we are interested in by the horizontal part of the displacement. To get height at the point we are actually interested in we have to use an iterative process. It's explaint closer to the end of the video.

**Comment by davidAlgis** [comment]
Hi, thanks for your answer and thanks for the details you give here. These details plus the end of the video, makes it clear now.
